language: node_js
node_js: 12
env:
  GITHUB_NAME: "Avi Sharvit"
  GITHUB_EMAIL: sharvita@gmail.com
before_install:
  - git config --global user.email "${GITHUB_EMAIL}"
  - git config --global user.name "${GITHUB_NAME}"
script: yarn build
deploy:
  on:
    branch: develop
  provider: script
  skip_cleanup: true
  script: yarn deploy
