name: Test workflow

on: ["push", "pull_request"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: [10.x, 12.x, 14.x]
    steps:
      - name: Use Node.js ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
