name: Test workflow

on: ["push", "pull_request"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
